### ISSUE TITLE
Team Norman Borlaug Code Review

### ISSUE THREAD

**Issue by willflee01** [vishalival/eep153-norman-borlaug#2]
Hello Team Norman Borlaug:

Overall, a really great start to the project! The presentation of the code is super stream-lined however overall I’m worried about your policy goal implementation. Other than that, I appreciated the header for every project, the descriptions under every header, and the streamlined way to access the datahub link.

General:
Just make sure the name of the Deliverables and number of the deliverable line up; some of them weren’t entirely accurate and caused me a little confusion

Deliverable 1.4[A] Estimate Demand System
- Just for readability purposes, it might be helpful to move all the demand systems under the header you made since they’re already created.
- While you have the Marshallian and Hicks curve, it might be helpful to incorporate more demand curves to the ones you’ve used as shown in class.

Deliverable 1.6[A] Construct Nutrient System
There are issues with your code being able to read columns[‘ t’ and ‘m’] from your uganda_p_df dataframe. It seems this dataframe has multiple names, particularly the name j for your index too, which is why the issue is being caused. 

Deliverable 1.7 [B] Policy Options: 
After reading over your policy options, I don’t believe they follow what’s in line with what’s asked for by the Project. In fact, I believe if you looked into what’s being asked for by Deliverable 1.9 [C] Value of Technical Innovation, it’s more in line with your GMO solution. The policy option your deliverable addresses should be to impact prices or budgets, neither of which is addressed by genetically modifying the food to fit the nutritional goals you want. However, if the professor has approved this project, go for it since it seems like an interesting way to improve the nutritional goals of the impacted populations. 

Anyways, super neat code and interesting start! Looking forward to your presentation!

**Comment by vishalival** [comment]
Hi, 

Thanks for the feedback! I appreciate the comments about the deliverable names and numbers - this will be helpful for final edits, and thanks for catching that. I was thinking of adding in Engel curves if I have the time, so thanks for that suggestion!
For the `Construct Nutrient System` comment, the issue is that the code cannot be run multiple times again (it needs to be run in one shot). It's an issue with it having multiple names, and I'll probably have to change the code so that it doesn't error in the future.

In terms of your feedback on our Policy Option, we understand that it's not impacting prices/budgets, but the Professor approved it for the Policy Option deliverable, since it's a more interesting take. I actually did this same project for Project 3 and went ahead by doubling budgets for the counterfactual experiments, but it didn't end up doing much. We were interested in doing something that actually would lead to higher nutritional outcomes that was more feasible than simply raising household budgets, and we thought that GMO food fortification would be the best way to go about. Also, both populations are super inelastic, so going about with the GMO fortification would be the best since they hardly change their buying habits in the first place.

Thank you so much!
